### ISSUE TITLE
http.Client has no field or method CloseIdleConnections

### ISSUE THREAD

**Issue by armendzz** [root-gg/plik#295]
Plik 1.3-RC1 with go go1.10.4 linux/amd64
Commit 70a9ecba749af3b44e310018f61e958b034d7f10 mint=true release=false
Building Plik client for darwin-386 to ../clients/darwin-386/plik
progress.go:14:2: cannot find package "github.com/camathieu/pb" in any of:
	/usr/lib/go-1.10/src/github.com/camathieu/pb (from $GOROOT)
	/root/go/src/github.com/camathieu/pb (from $GOPATH)
plik.go:17:2: cannot find package "github.com/docopt/docopt-go" in any of:
	/usr/lib/go-1.10/src/github.com/docopt/docopt-go (from $GOROOT)
	/root/go/src/github.com/docopt/docopt-go (from $GOPATH)
......

plik.go:19:2: cannot find package "github.com/olekukonko/ts" in any of:
	/usr/lib/go-1.10/src/github.com/olekukonko/ts (from $GOROOT)
	/root/go/src/github.com/olekukonko/ts (from $GOPATH)
md5sum: ../clients/windows-386/plik.exe: No such file or directory
Plik 1.3-RC1 with go go1.10.4 linux/amd64
Commit 70a9ecba749af3b44e310018f61e958b034d7f10 mint=true release=false
Building Plik server
# github.com/minio/minio-go
/root/go/src/github.com/minio/minio-go/api.go:569:16: c.httpClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
# github.com/root-gg/plik/server/handlers
/root/go/src/github.com/root-gg/plik/server/handlers/misc.go:18:33: undefined: common.GetBuildInfo
Makefile:37: recipe for target 'server' failed
make: *** [server] Error 2

**Comment by camathieu** [comment]
Hello, can you try to build with go1.14 ?
